# Refer to golangci-lint's example config file for more options and information:
# https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml

run:
  timeout: 2m
  modules-download-mode: readonly
  issues-exit-code: 2
  tests: true
  allow-parallel-runners: true
  go: "1.21"

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - forcetypeassert
    - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - grouper
    - importas
    - ineffassign
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagalign
    - tagliatelle
    - tenv
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace

linters-settings:
  varnamelen:
    max-distance: 6
    min-name-length: 2
    ignore-names:
      - tc

  tagliatelle:
    # Check the struct tag name case.
    case:
      use-field-name: false
      rules:
        json: snake
  nlreturn:
    block-size: 4
  godot:
    exclude:
      - "^todo:"
    period: false
  thelper:
    test:
      begin: false
    benchmark:
      begin: false
  paralleltest:
    ignore-missing: true
  whitespace:
    multi-if: true
    multi-func: true
  tagalign:
    align: false
  funlen:
    lines: 80
    ignore-comments: true
  exhaustive:
    default-signifies-exhaustive: true
